---
title: "Thriving at work - Online Appendix"
author: "[authors blinded for review]"
date: '`r Sys.Date()`'
bibliography: ./refs/refs.bib
csl: ./refs/apa7.csl
mainfont: Times New Roman
output:
  html_document:
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float: yes
    df_print: paged
---

```{r, include = FALSE}
DOCNAME <- "Integrate"
knitr::opts_chunk$set(autodep        = TRUE,
                      cache          = TRUE,
                      cache.path     = paste0("cache/", DOCNAME, "/"),
                      cache.comments = TRUE,
                      echo           = FALSE,
                      error          = FALSE,
                      fig.align      = "center",
                      fig.path       = paste0("figures/", DOCNAME, "/"),
                      fig.width      = 10,
                      fig.height     = 8,
                      message        = FALSE,
                      warning        = FALSE)
```

```{r libraries, cache = FALSE, include = FALSE}

packages <- c("mediation", "foreign", "tidyverse","stargazer","multicon", "ggplot2", "plyr", "reshape2", "readxl", "haven", "sjlabelled", "janitor",
              "scales", "grid", "tidyLPA", "Rcpp", "naniar", "dplyr", "car", "mice", "lubridate", "zoo", "purrr", "rlang", "mgsub", "datapasta", "stringr",
              "rstudioapi", "labelled", "modi", "semPlot", "kulife", "knitr", "janitor", "DT", "sjlabelled", "kableExtra", 
              "glue", "numform", "xtable", "officer", "Hmisc",
              "lme4", "lmerTest", "RSA", "gridExtra", "MuMIn", "misty", "performance",
              "sjlabelled", "kableExtra", "flextable", "sjPlot", "reprex", "datapasta", "semoutput", "semTools",
              "merTools", "xlsx")

source("./R/remote_functions.R")
source("./R/MultilevelRSA.r")

ipak(packages)

```

```{r get_data, cache = FALSE, include = FALSE}
options(knitr.table.format = function() {
  if (knitr::is_latex_output()) 'latex' else 'pandoc'
})

files <- dir("../data", pattern = "\\.sav$", full.names = FALSE) 
df_list <- vector("list", length(files))
names(df_list) <- files

df_list <- read_in(files, directory = "../data/")

list2env(df_list,envir=.GlobalEnv)


```


```{r session-info, cache = FALSE, include = FALSE}
devtools::session_info()
```

```{r cleanup-docs, cache = FALSE, include = FALSE}
doc.files <- c(list.files(pattern = "pdf"),
               list.files(pattern = "html"),
               list.files(pattern = "docx"))

for (file in doc.files) {
    file.rename(file, file.path("./docs", file))
}
```

```{r, include=FALSE}
Thriving_analyses <- TRUE
Online_appendix <- TRUE
```

```{r, child=if (Thriving_analyses) './analysis/Thriving_analyses.Rmd'}
```

```{r, child=if (Online_appendix) './analysis/Online_appendix.Rmd'}
```
